# Generated by Django 3.2.2 on 2021-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=255)),
                ('linkedLn', models.URLField()),
                ('photo', models.ImageField(upload_to='staff/')),
            ],
        ),
    ]
