

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text4', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text5', models.TextField(blank=True)),
                ('text5_ru', models.TextField(blank=True, null=True)),
                ('text5_en', models.TextField(blank=True, null=True)),
                ('text5_uz', models.TextField(blank=True, null=True)),
                ('text6', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text7', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text8', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text9', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('text9_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text9_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text9_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BakModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True, max_length=255)),
                ('text2_ru', models.TextField(blank=True, max_length=255, null=True)),
                ('text2_en', models.TextField(blank=True, max_length=255, null=True)),
                ('text2_uz', models.TextField(blank=True, max_length=255, null=True)),
                ('text3', models.CharField(blank=True, max_length=255)),
                ('text3_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text4', models.ImageField(blank=True, upload_to='pages/')),
                ('text5', models.TextField(blank=True, max_length=255)),
                ('text5_ru', models.TextField(blank=True, max_length=255, null=True)),
                ('text5_en', models.TextField(blank=True, max_length=255, null=True)),
                ('text5_uz', models.TextField(blank=True, max_length=255, null=True)),
                ('text6', models.ImageField(blank=True, upload_to='pages/')),
                ('text7', models.TextField(blank=True, max_length=255)),
                ('text7_ru', models.TextField(blank=True, max_length=255, null=True)),
                ('text7_en', models.TextField(blank=True, max_length=255, null=True)),
                ('text7_uz', models.TextField(blank=True, max_length=255, null=True)),
                ('text8', models.ImageField(blank=True, upload_to='pages/')),
                ('text9', models.TextField(blank=True, max_length=255)),
                ('text9_ru', models.TextField(blank=True, max_length=255, null=True)),
                ('text9_en', models.TextField(blank=True, max_length=255, null=True)),
                ('text9_uz', models.TextField(blank=True, max_length=255, null=True)),
                ('text10', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('text10_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text10_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text10_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text11', models.TextField(blank=True, max_length=255)),
                ('text11_ru', models.TextField(blank=True, max_length=255, null=True)),
                ('text11_en', models.TextField(blank=True, max_length=255, null=True)),
                ('text11_uz', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConferencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('text3_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text3_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text3_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('text4_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text4_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text4_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text5', models.CharField(default='', max_length=255)),
                ('text5_ru', models.CharField(default='', max_length=255, null=True)),
                ('text5_en', models.CharField(default='', max_length=255, null=True)),
                ('text5_uz', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=20)),
                ('text2', models.CharField(blank=True, max_length=20)),
                ('text3', models.CharField(blank=True, max_length=20)),
                ('text4', models.CharField(blank=True, max_length=255)),
                ('text5', models.CharField(blank=True, max_length=255)),
                ('text5_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_uz', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateConferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('text3_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text3_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text3_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text4', models.CharField(default='', max_length=255)),
                ('text4_ru', models.CharField(default='', max_length=255, null=True)),
                ('text4_en', models.CharField(default='', max_length=255, null=True)),
                ('text4_uz', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.ImageField(blank=True, upload_to='design/')),
                ('text4', models.CharField(blank=True, max_length=255)),
                ('text4_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text5', models.TextField(blank=True)),
                ('text5_ru', models.TextField(blank=True, null=True)),
                ('text5_en', models.TextField(blank=True, null=True)),
                ('text5_uz', models.TextField(blank=True, null=True)),
                ('text6', models.ImageField(blank=True, upload_to='design/')),
                ('text7', models.CharField(blank=True, max_length=255)),
                ('text7_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text8', models.TextField(blank=True)),
                ('text8_ru', models.TextField(blank=True, null=True)),
                ('text8_en', models.TextField(blank=True, null=True)),
                ('text8_uz', models.TextField(blank=True, null=True)),
                ('text9', models.ImageField(blank=True, upload_to='design/')),
                ('text10', models.CharField(blank=True, max_length=255)),
                ('text10_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text10_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text10_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text11', models.TextField(blank=True)),
                ('text11_ru', models.TextField(blank=True, null=True)),
                ('text11_en', models.TextField(blank=True, null=True)),
                ('text11_uz', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('text3_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text3_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text3_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text4', models.CharField(blank=True, max_length=255)),
                ('text4_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_uz', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LangEditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(blank=True)),
                ('text1_ru', models.TextField(blank=True, null=True)),
                ('text1_en', models.TextField(blank=True, null=True)),
                ('text1_uz', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.CharField(blank=True, max_length=100)),
                ('text3_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text3_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text3_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text4', models.CharField(blank=True, max_length=100)),
                ('text5', models.CharField(blank=True, max_length=100)),
                ('text5_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text5_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text6', models.CharField(blank=True, max_length=100)),
                ('text7', models.CharField(blank=True, max_length=100)),
                ('text7_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text8', models.CharField(blank=True, max_length=100)),
                ('text9', models.CharField(blank=True, max_length=100)),
                ('text9_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text9_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text9_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text10', models.CharField(blank=True, max_length=100)),
                ('text10_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text10_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text10_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text11', models.CharField(blank=True, max_length=100)),
                ('text11_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text11_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text11_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text12', models.CharField(blank=True, max_length=100)),
                ('text12_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text12_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text12_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text13', models.CharField(blank=True, max_length=100)),
                ('text13_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text13_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text13_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text14', models.CharField(blank=True, max_length=100)),
                ('text14_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text14_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text14_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text15', models.CharField(blank=True, max_length=100)),
                ('text15_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text15_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text15_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text16', models.CharField(blank=True, max_length=100)),
                ('text16_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text16_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text16_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text17', models.CharField(blank=True, max_length=100)),
                ('text17_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text17_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text17_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text18', models.CharField(blank=True, max_length=100)),
                ('text18_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text18_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text18_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text19', models.CharField(blank=True, max_length=100)),
                ('text19_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text19_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text19_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text20', models.CharField(blank=True, max_length=100)),
                ('text20_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text20_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text20_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text21', models.CharField(blank=True, max_length=100)),
                ('text21_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text21_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text21_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text22', models.CharField(blank=True, max_length=100)),
                ('text22_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text22_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text22_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text23', models.CharField(blank=True, max_length=100)),
                ('text23_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text23_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text23_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text24', models.CharField(blank=True, max_length=100)),
                ('text24_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text24_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text24_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text25', models.CharField(blank=True, max_length=100)),
                ('text25_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text25_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text25_uz', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('text3_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text3_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text3_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text4', models.CharField(blank=True, max_length=255)),
                ('text4_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_uz', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProofModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.CharField(blank=True, max_length=255)),
                ('text3_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text4', models.TextField(blank=True)),
                ('text4_ru', models.TextField(blank=True, null=True)),
                ('text4_en', models.TextField(blank=True, null=True)),
                ('text4_uz', models.TextField(blank=True, null=True)),
                ('text5', models.CharField(blank=True, max_length=255)),
                ('text5_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text6', models.TextField(blank=True)),
                ('text6_ru', models.TextField(blank=True, null=True)),
                ('text6_en', models.TextField(blank=True, null=True)),
                ('text6_uz', models.TextField(blank=True, null=True)),
                ('text7', models.CharField(blank=True, max_length=255)),
                ('text7_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text8', models.TextField(blank=True)),
                ('text8_ru', models.TextField(blank=True, null=True)),
                ('text8_en', models.TextField(blank=True, null=True)),
                ('text8_uz', models.TextField(blank=True, null=True)),
                ('text9', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text9_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text9_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text9_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStrategyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text1_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text1_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text1_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text2_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text2_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text2_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text3', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text3_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text3_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text3_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text4', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text4_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text4_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text4_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text5', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text5_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text5_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text5_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text6', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text6_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text6_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text6_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text7', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text7_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text7_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text7_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text8', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text8_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text8_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text8_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text9', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text9_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text9_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text9_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScopusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text4', models.ImageField(blank=True, upload_to='pages/')),
                ('text5', models.TextField(blank=True)),
                ('text5_ru', models.TextField(blank=True, null=True)),
                ('text5_en', models.TextField(blank=True, null=True)),
                ('text5_uz', models.TextField(blank=True, null=True)),
                ('text6', models.ImageField(blank=True, upload_to='pages/')),
                ('text7', models.TextField(blank=True)),
                ('text7_ru', models.TextField(blank=True, null=True)),
                ('text7_en', models.TextField(blank=True, null=True)),
                ('text7_uz', models.TextField(blank=True, null=True)),
                ('text8', models.ImageField(blank=True, upload_to='pages/')),
                ('text9', models.TextField(blank=True)),
                ('text9_ru', models.TextField(blank=True, null=True)),
                ('text9_en', models.TextField(blank=True, null=True)),
                ('text9_uz', models.TextField(blank=True, null=True)),
                ('text10', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text10_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text10_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text10_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text11', models.CharField(blank=True, max_length=255)),
                ('text11_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text11_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text11_uz', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text2_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text2_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text2_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text3', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text3_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text3_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text3_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text4', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text4_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text4_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text4_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text5', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_uz', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebinarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, upload_to='changes/')),
            ],
        ),
    ]
