# Generated by Django 3.2.2 on 2021-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=30, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text3', models.CharField(blank=True, max_length=30, null=True)),
                ('text4', models.CharField(blank=True, max_length=30, null=True)),
                ('text5', models.TextField()),
                ('text6', models.CharField(blank=True, max_length=30, null=True)),
                ('text7', models.CharField(blank=True, max_length=30, null=True)),
                ('text8', models.CharField(blank=True, max_length=30, null=True)),
                ('text9', models.TextField()),
                ('text10', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
