# Generated by Django 3.2.2 on 2021-07-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
