# Generated by Django 3.2.2 on 2021-08-07 14:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langeditmodel',
            name='text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='langeditmodel',
            name='text2_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='langeditmodel',
            name='text2_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='langeditmodel',
            name='text2_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='langeditmodel',
            name='text9',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='langeditmodel',
            name='text9_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='langeditmodel',
            name='text9_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='langeditmodel',
            name='text9_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
