# Generated by Django 3.2.2 on 2021-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangEditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=100)),
                ('text1_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text2', models.TextField()),
                ('text2_ru', models.TextField(null=True)),
                ('text2_en', models.TextField(null=True)),
                ('text2_uz', models.TextField(null=True)),
                ('text3', models.CharField(blank=True, max_length=100)),
                ('text3_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text3_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text3_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text4', models.CharField(blank=True, max_length=100)),
                ('text5', models.CharField(blank=True, max_length=100)),
                ('text5_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text5_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text6', models.CharField(blank=True, max_length=100)),
                ('text6_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text6_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text6_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text7', models.CharField(blank=True, max_length=100)),
                ('text7_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text8', models.CharField(blank=True, max_length=100)),
                ('text8_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text8_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text8_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('text9', models.CharField(blank=True, max_length=100)),
                ('text9_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text9_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text9_uz', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
