# Generated by Django 3.2.2 on 2021-08-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0002_langeditmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='langeditmodel',
            old_name='text6_en',
            new_name='text4_en',
        ),
        migrations.RenameField(
            model_name='langeditmodel',
            old_name='text6_ru',
            new_name='text4_ru',
        ),
        migrations.RenameField(
            model_name='langeditmodel',
            old_name='text6_uz',
            new_name='text4_uz',
        ),
        migrations.RemoveField(
            model_name='langeditmodel',
            name='text7_en',
        ),
        migrations.RemoveField(
            model_name='langeditmodel',
            name='text7_ru',
        ),
        migrations.RemoveField(
            model_name='langeditmodel',
            name='text7_uz',
        ),
        migrations.RemoveField(
            model_name='langeditmodel',
            name='text8_en',
        ),
        migrations.RemoveField(
            model_name='langeditmodel',
            name='text8_ru',
        ),
        migrations.RemoveField(
            model_name='langeditmodel',
            name='text8_uz',
        ),
    ]
