# Generated by Django 3.2.2 on 2021-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0002_auto_20210718_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='text11',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text9',
            field=models.TextField(blank=True),
        ),
    ]
