# Generated by Django 3.2.2 on 2021-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0003_auto_20210718_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
