# Generated by Django 3.2.2 on 2021-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0004_alter_aboutusmodel_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='text10_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text10_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text10_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text11_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text11_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text11_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text1_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text3_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text3_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text3_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text4_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text4_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text4_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text5_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text5_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text5_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text6_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text6_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text6_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text7_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text7_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text7_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text8_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text8_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text8_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text9_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text9_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text9_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
