# Generated by Django 3.2.2 on 2021-09-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0005_webinarsurls1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakmodel',
            name='text11',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text5_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text5_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text5_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text7_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text7_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text7_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text9_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text9_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text9_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
