# Generated by Django 3.2.2 on 2021-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0005_auto_20210718_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='changes/')),
            ],
        ),
    ]
