# Generated by Django 3.2.2 on 2021-10-11 02:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0006_auto_20210907_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPlatformsContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('context_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('context_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('context_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
