# Generated by Django 3.2.2 on 2021-07-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0006_webinarsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarsmodel',
            name='text1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinarsmodel',
            name='text1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinarsmodel',
            name='text1_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinarsmodel',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinarsmodel',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinarsmodel',
            name='text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
