# Generated by Django 3.2.2 on 2021-07-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0007_auto_20210721_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True)),
                ('text3_ru', models.TextField(blank=True, null=True)),
                ('text3_en', models.TextField(blank=True, null=True)),
                ('text3_uz', models.TextField(blank=True, null=True)),
                ('text4', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text5', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text6', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text7', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text8', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_uz', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
