# Generated by Django 3.2.2 on 2021-07-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0007_conferencesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=20)),
                ('text2', models.CharField(blank=True, max_length=20)),
                ('text3', models.CharField(blank=True, max_length=20)),
                ('text4', models.CharField(blank=True, max_length=255)),
                ('text5', models.CharField(blank=True, max_length=255)),
                ('text5_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text5_uz', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
