# Generated by Django 3.2.2 on 2021-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0008_translationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.ImageField(blank=True, upload_to='design/')),
                ('text4', models.CharField(blank=True, max_length=255)),
                ('text4_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text5', models.TextField(blank=True)),
                ('text5_ru', models.TextField(blank=True, null=True)),
                ('text5_en', models.TextField(blank=True, null=True)),
                ('text5_uz', models.TextField(blank=True, null=True)),
                ('text6', models.ImageField(blank=True, upload_to='design/')),
                ('text7', models.CharField(blank=True, max_length=255)),
                ('text7_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text8', models.TextField(blank=True)),
                ('text8_ru', models.TextField(blank=True, null=True)),
                ('text8_en', models.TextField(blank=True, null=True)),
                ('text8_uz', models.TextField(blank=True, null=True)),
                ('text9', models.ImageField(blank=True, upload_to='design/')),
                ('text10', models.CharField(blank=True, max_length=255)),
                ('text10_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text10_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text10_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text11', models.TextField(blank=True)),
                ('text11_ru', models.TextField(blank=True, null=True)),
                ('text11_en', models.TextField(blank=True, null=True)),
                ('text11_uz', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
