# Generated by Django 3.2.2 on 2021-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0012_auto_20210722_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True)),
                ('text3_ru', models.TextField(blank=True, null=True)),
                ('text3_en', models.TextField(blank=True, null=True)),
                ('text3_uz', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True)),
                ('text4_ru', models.TextField(blank=True, null=True)),
                ('text4_en', models.TextField(blank=True, null=True)),
                ('text4_uz', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True)),
                ('text5_ru', models.TextField(blank=True, null=True)),
                ('text5_en', models.TextField(blank=True, null=True)),
                ('text5_uz', models.TextField(blank=True, null=True)),
                ('text6', models.CharField(blank=True, max_length=255)),
                ('text6_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text6_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text7', models.CharField(blank=True, max_length=255)),
                ('text7_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text7_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text8', models.CharField(blank=True, max_length=255)),
                ('text8_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text8_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text9', models.CharField(blank=True, max_length=255)),
                ('text9_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text9_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text9_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text10', models.TextField(blank=True)),
                ('text10_ru', models.TextField(blank=True, null=True)),
                ('text10_en', models.TextField(blank=True, null=True)),
                ('text10_uz', models.TextField(blank=True, null=True)),
                ('text11', models.TextField(blank=True)),
                ('text11_ru', models.TextField(blank=True, null=True)),
                ('text11_en', models.TextField(blank=True, null=True)),
                ('text11_uz', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
