# Generated by Django 3.2.2 on 2021-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0014_scopusmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text3_en',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text3_ru',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text3_uz',
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text3',
            field=models.ImageField(blank=True, upload_to='scopus'),
        ),
    ]
