# Generated by Django 3.2.2 on 2021-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0015_auto_20210722_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text11',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text11_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text11_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text11_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text12',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text12_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text12_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text12_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text13',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text13_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text13_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text13_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text14',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text14_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text14_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text14_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text15',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text15_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text15_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text15_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text16',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text16_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text16_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text16_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text5_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text5_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text5_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text7_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text7_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text7_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text9_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text9_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text9_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
