# Generated by Django 3.2.2 on 2021-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0018_langeditmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='langeditmodel',
            name='text25',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='langeditmodel',
            name='text25_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langeditmodel',
            name='text25_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langeditmodel',
            name='text25_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
