# Generated by Django 3.2.2 on 2021-07-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0008_translationmodel'),
        ('setpage', '0019_auto_20210723_1605'),
    ]

    operations = [
    ]
