# Generated by Django 3.2.2 on 2021-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0020_merge_0008_translationmodel_0019_auto_20210723_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStrategyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(blank=True)),
                ('text1_ru', models.TextField(blank=True, null=True)),
                ('text1_en', models.TextField(blank=True, null=True)),
                ('text1_uz', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True)),
                ('text3_ru', models.TextField(blank=True, null=True)),
                ('text3_en', models.TextField(blank=True, null=True)),
                ('text3_uz', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True)),
                ('text4_ru', models.TextField(blank=True, null=True)),
                ('text4_en', models.TextField(blank=True, null=True)),
                ('text4_uz', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True)),
                ('text5_ru', models.TextField(blank=True, null=True)),
                ('text5_en', models.TextField(blank=True, null=True)),
                ('text5_uz', models.TextField(blank=True, null=True)),
                ('text6', models.TextField(blank=True)),
                ('text6_ru', models.TextField(blank=True, null=True)),
                ('text6_en', models.TextField(blank=True, null=True)),
                ('text6_uz', models.TextField(blank=True, null=True)),
                ('text7', models.TextField(blank=True)),
                ('text7_ru', models.TextField(blank=True, null=True)),
                ('text7_en', models.TextField(blank=True, null=True)),
                ('text7_uz', models.TextField(blank=True, null=True)),
                ('text8', models.TextField(blank=True)),
                ('text8_ru', models.TextField(blank=True, null=True)),
                ('text8_en', models.TextField(blank=True, null=True)),
                ('text8_uz', models.TextField(blank=True, null=True)),
                ('text9', models.CharField(blank=True, max_length=100)),
                ('text9_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text9_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text9_uz', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
