# Generated by Django 3.2.2 on 2021-08-03 11:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0022_auto_20210803_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofmodel',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text10_en',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text10_ru',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text10_uz',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text11',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text11_en',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text11_ru',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text11_uz',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text12',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text12_en',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text12_ru',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text12_uz',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text13',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text13_en',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text13_ru',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='text13_uz',
        ),
        migrations.AlterField(
            model_name='proofmodel',
            name='text9',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='proofmodel',
            name='text9_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='proofmodel',
            name='text9_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='proofmodel',
            name='text9_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
