# Generated by Django 3.2.2 on 2021-08-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0008_contactmodel'),
        ('setpage', '0023_auto_20210803_1652'),
    ]

    operations = [
    ]
