# Generated by Django 3.2.2 on 2021-08-03 15:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0024_merge_0008_contactmodel_0023_auto_20210803_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateConferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255)),
                ('text1_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text1_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.TextField(blank=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('text2_en', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('text3_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text3_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text3_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('text4', models.CharField(default='', max_length=255)),
                ('text4_ru', models.CharField(default='', max_length=255, null=True)),
                ('text4_en', models.CharField(default='', max_length=255, null=True)),
                ('text4_uz', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
