# Generated by Django 3.2.2 on 2021-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0027_auto_20210803_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesmodel',
            name='text5_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conferencesmodel',
            name='text5_ru',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conferencesmodel',
            name='text5_uz',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
