# Generated by Django 3.2.2 on 2021-08-03 16:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0028_auto_20210803_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantsmodel',
            name='text3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='grantsmodel',
            name='text3_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantsmodel',
            name='text3_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantsmodel',
            name='text3_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantsmodel',
            name='text4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='grantsmodel',
            name='text4_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grantsmodel',
            name='text4_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grantsmodel',
            name='text4_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
