# Generated by Django 3.2.2 on 2021-08-04 08:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0029_auto_20210803_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patentmodel',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text10_en',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text10_ru',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text10_uz',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text11',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text11_en',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text11_ru',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text11_uz',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text5_en',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text5_ru',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text5_uz',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text6_en',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text6_ru',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text6_uz',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text7_en',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text7_ru',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text7_uz',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text8_en',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text8_ru',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text8_uz',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text9',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text9_en',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text9_ru',
        ),
        migrations.RemoveField(
            model_name='patentmodel',
            name='text9_uz',
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text3_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text3_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text3_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text4_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text4_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patentmodel',
            name='text4_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
