# Generated by Django 3.2.2 on 2021-08-04 09:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0030_auto_20210804_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakmodel',
            name='text12',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text12_en',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text12_ru',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text12_uz',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text13',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text13_en',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text13_ru',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text13_uz',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text14',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text14_en',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text14_ru',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text14_uz',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text15',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text15_en',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text15_ru',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text15_uz',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text16',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text16_en',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text16_ru',
        ),
        migrations.RemoveField(
            model_name='bakmodel',
            name='text16_uz',
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
