# Generated by Django 3.2.2 on 2021-08-04 10:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0031_auto_20210804_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text12',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text12_en',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text12_ru',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text12_uz',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text13',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text13_en',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text13_ru',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text13_uz',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text14',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text14_en',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text14_ru',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text14_uz',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text15',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text15_en',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text15_ru',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text15_uz',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text16',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text16_en',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text16_ru',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text16_uz',
        ),
        migrations.RemoveField(
            model_name='scopusmodel',
            name='text3',
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text10',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text10_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text10_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text10_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bakmodel',
            name='text11_uz',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='scopusmodel',
            name='text10_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
