# Generated by Django 3.2.2 on 2021-08-04 11:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0032_auto_20210804_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationmodel',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text6_en',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text6_ru',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text6_uz',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text7_en',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text7_ru',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text7_uz',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text8_en',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text8_ru',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='text8_uz',
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text2_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text2_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text2_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text3',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text3_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text3_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text3_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text4',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text4_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text4_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='text4_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
