# Generated by Django 3.2.2 on 2021-08-05 13:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setpage', '0033_auto_20210804_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text10_en',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text10_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text10_uz',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text11',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text11_en',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text11_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='text11_uz',
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text9',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text9_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text9_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text9_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
