# Generated by Django 3.2.2 on 2021-06-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
