# Generated by Django 3.2.2 on 2021-06-14 10:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='material_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='others_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='author_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='more_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
