# Generated by Django 3.2.6 on 2021-08-09 18:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, upload_to='news/')),
                ('material_name', models.CharField(max_length=100)),
                ('material_name_ru', models.CharField(max_length=100, null=True)),
                ('material_name_en', models.CharField(max_length=100, null=True)),
                ('material_name_uz', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('others', ckeditor_uploader.fields.RichTextUploadingField()),
                ('others_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('others_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('others_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-id',),
            },
        ),
    ]
