# Generated by Django 3.2 on 2021-05-06 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='news/')),
                ('material_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('others', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='getpatent',
            options={'verbose_name': 'Patent', 'verbose_name_plural': 'Patents'},
        ),
        migrations.CreateModel(
            name='PublicationToScopus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=255)),
                ('org_contacts', models.CharField(max_length=255)),
                ('org_address', models.CharField(max_length=255)),
                ('application_upload', models.FileField(upload_to='app_requests/')),
                ('is_agree', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication to Scopus',
                'verbose_name_plural': 'Scopus Publications',
            },
        ),
        migrations.CreateModel(
            name='PublicationToMagazines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.CharField(max_length=255)),
                ('org_contacts', models.CharField(max_length=255)),
                ('org_address', models.CharField(max_length=255)),
                ('is_agree', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizeResearches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('select_topic', models.CharField(choices=[('стратегия исследования', 'стратегия исследования'), ('партнёрство и сотрудничество', 'партнёрство и сотрудничество'), ('финансирование', 'финансирование'), ('управление исследовательским процессом', 'управление исследовательским процессом'), ('общая консультация', 'общая консультация')], max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('org_contacts', models.CharField(max_length=255)),
                ('org_address', models.CharField(max_length=255)),
                ('is_agree', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderToGraphicalMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=255)),
                ('org_contacts', models.CharField(max_length=255)),
                ('org_address', models.CharField(max_length=255)),
                ('is_agree', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReviewForDissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astronomy', models.CharField(blank=True, max_length=255)),
                ('biology', models.CharField(blank=True, max_length=255)),
                ('business', models.CharField(blank=True, max_length=255)),
                ('chemistry', models.CharField(blank=True, max_length=255)),
                ('ecology', models.CharField(blank=True, max_length=255)),
                ('engineering', models.CharField(blank=True, max_length=255)),
                ('medicine', models.CharField(blank=True, max_length=255)),
                ('physics', models.CharField(blank=True, max_length=255)),
                ('social_science', models.CharField(blank=True, max_length=255)),
                ('other', models.CharField(blank=True, max_length=255)),
                ('additional_comment', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('science_degree', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('material_name', models.CharField(max_length=255)),
                ('supervisor_name', models.CharField(max_length=255)),
                ('is_agree', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
