# Generated by Django 3.2.2 on 2021-05-10 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_topresearches'),
    ]

    operations = [
        migrations.AddField(
            model_name='topresearches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
