# Generated by Django 3.2.2 on 2021-08-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_topic_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
