# Generated by Django 3.2.2 on 2021-07-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_topic_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standart', models.IntegerField(default=240)),
                ('express', models.IntegerField(default=300)),
                ('premium', models.IntegerField(default=400)),
            ],
            options={
                'verbose_name': 'Cost Model',
                'verbose_name_plural': 'Cost Model',
            },
        ),
    ]
