# Generated by Django 3.2.2 on 2021-08-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_about_us_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='top_researches/')),
                ('material_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setpage.aboutusmodel')),
            ],
        ),
    ]
