# Generated by Django 3.2.2 on 2021-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_about_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us_news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_news/'),
        ),
        migrations.AddField(
            model_name='about_us_news',
            name='material_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_us_news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us_news',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='About_news',
        ),
    ]
