# Generated by Django 3.2.2 on 2021-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_costmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2555)),
                ('sub_text', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
