# Generated by Django 3.2.2 on 2021-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210609_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='topresearches',
            name='author_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='author_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='author_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='more_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='more_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='more_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topresearches',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
