# Generated by Django 3.2.2 on 2021-08-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210802_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us_news',
            name='name',
        ),
    ]
