# Generated by Django 3.2.2 on 2021-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_en',
            field=models.CharField(max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_ru',
            field=models.CharField(max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_uz',
            field=models.CharField(max_length=2555, null=True),
        ),
    ]
