# Generated by Django 3.2.2 on 2021-08-05 13:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_about_us_news_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('stendart', models.BooleanField()),
                ('express', models.BooleanField()),
                ('premium', models.BooleanField()),
            ],
        ),
    ]
