# Generated by Django 3.2.2 on 2021-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_about_us_news_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarsUrl1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='WebinarsUrl2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=225)),
            ],
        ),
    ]
