# Generated by Django 3.2.2 on 2021-08-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_tariffs'),
        ('pages', '0007_webinarsurl1_webinarsurl2'),
    ]

    operations = [
    ]
