# Generated by Django 3.2.2 on 2021-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255, verbose_name='transaction id')),
                ('request_id', models.IntegerField(verbose_name='request id')),
                ('order_id', models.IntegerField(verbose_name='order id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='state')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], default='processing', max_length=55, verbose_name='status')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('create_time', models.BigIntegerField(verbose_name='create time')),
                ('perform_time', models.BigIntegerField(default=0, verbose_name='perform time')),
                ('cancel_time', models.BigIntegerField(default=0, verbose_name='cancel time')),
                ('cancel_reason', models.IntegerField(blank=True, null=True, verbose_name='cancel reason')),
            ],
            options={
                'verbose_name': 'payme transaction',
                'verbose_name_plural': 'payme transactions',
            },
        ),
    ]
