# Generated by Django 3.2.2 on 2021-05-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpatent',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='ordertographicalmaterials',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='organizeresearches',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='publicationtomagazines',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='publicationtoscopus',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='researchgrant',
            name='fullname',
        ),
        migrations.AddField(
            model_name='getpatent',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='getpatent',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertographicalmaterials',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertographicalmaterials',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizeresearches',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizeresearches',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationtomagazines',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationtomagazines',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationtoscopus',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationtoscopus',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchgrant',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchgrant',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
