
# Generated by Django 3.2.2 on 2021-05-18 17:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20210518_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForFreeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),

                ('busyness', models.CharField(max_length=100)),
                ('place_of_work', models.CharField(max_length=100)),
                ('academic_degree', models.CharField(choices=[('кандидат наук', 'кандидат наук '), ('доктор наук', 'доктор  наук'), ('доктор философии', 'доктор философии PhD'), ('хабилитированный доктор', 'хабилитированный доктор (Dr. habil.)')], max_length=100)),
                ('application_name', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('upload_file', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],

        ),
    ]
