# Generated by Django 3.2.2 on 2021-05-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20210518_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForFreeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('busyness', models.CharField(max_length=50)),
                ('place_of_work', models.CharField(max_length=100)),
                ('academic_degree', models.CharField(choices=[('кандидат наук', 'кандидат наук '), ('доктор наук', 'доктор наук'), ('доктор философии', 'доктор философии PhD'), ('хабилитировании доктор', 'хабилитировании доктор (Dr. habil)')], max_length=100)),
                ('article_title', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('file_upload', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name': 'Заявка на бесплатную консультацию',
                'verbose_name_plural': 'Бесплатный Kонсультации',
            },
        ),
    ]
