# Generated by Django 3.2.2 on 2021-05-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_applicationforfreeconsultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationforfreeconsultation',
            options={'verbose_name': 'Заявка на бесплатную консультацию', 'verbose_name_plural': 'Бесплатный Kонсультации'},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='material',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='organization_contacts',
        ),
        migrations.AddField(
            model_name='consultation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
