# Generated by Django 3.2.2 on 2021-05-24 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_proofreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
