# Generated by Django 3.2.2 on 2021-06-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_peerreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationforfreeconsultation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizeresearches',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peerreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proofreading',
            options={},
        ),
    ]
