# Generated by Django 3.2.2 on 2021-06-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_auto_20210602_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
