# Generated by Django 3.2.2 on 2021-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0023_auto_20210608_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultation',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
