# Generated by Django 3.2.2 on 2021-07-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('is_agree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
