# Generated by Django 3.2.6 on 2021-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='research_area',
            field=models.CharField(choices=[('АСТРОНОМИЯ И ПЛАНЕТОЛОГИЯ', 'АСТРОНОМИЯ И ПЛАНЕТОЛОГИЯ'), ('БИОЛОГИЯ', 'БИОЛОГИЯ'), ('БИЗНЕС', 'БИЗНЕС'), ('ХИМИЯ', 'ХИМИЯ'), ('ЭКОЛОГИЯ И НАУКА О ЗЕМЛЕ', 'ЭКОЛОГИЯ И НАУКА О ЗЕМЛЕ'), ('ИНЖЕНЕРИЯ', 'ИНЖЕНЕРИЯ'), ('МЕДИЦИНА', 'МЕДИЦИНА'), ('ФИЗИКА', 'ФИЗИКА'), ('СОЦИАЛЬНЫЕ НАУКИ', 'СОЦИАЛЬНЫЕ НАУКИ'), ('ДРУГОЕ', 'ДРУГОЕ')], max_length=100),
        ),
    ]
