# Generated by Django 3.2.2 on 2021-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0003_auto_20210510_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('material', models.CharField(choices=[('стратегия исследования', 'стратегия исследования'), ('партнёрство и сотрудничество', 'партнёрство и сотрудничество'), ('финансирование', 'финансирование'), ('управление исследовательским процессом', 'управление исследовательским процессом'), ('общая консультация', 'общая консультация')], max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('organization_contacts', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
