# Generated by Django 3.2.2 on 2021-07-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0003_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'language_editing', 'verbose_name_plural': 'language_editing'},
        ),
        migrations.AlterField(
            model_name='applicationforfreeconsultation',
            name='academic_degree',
            field=models.CharField(choices=[('Кандидат наук', 'Кандидат наук '), ('Доктор наук', 'Доктор  наук'), ('Доктор философии', 'Доктор философии PhD'), ('Хабилитированный доктор', 'Хабилитированный доктор (Dr. habil.)')], max_length=100),
        ),
    ]
