# Generated by Django 3.2.2 on 2021-08-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0003_alter_translation_research_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='baks',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='scopus',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
