# Generated by Django 3.2.2 on 2021-07-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0004_auto_20210729_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpatent',
            name='user',
        ),
    ]
