# Generated by Django 3.2.2 on 2021-08-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0004_auto_20210810_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='last_name',
        ),
    ]
