# Generated by Django 3.2.2 on 2021-05-18 04:38

from django.db import migrations, models
import my_requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0005_auto_20210517_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
