# Generated by Django 3.2.2 on 2021-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0005_remove_getpatent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getpatent',
            name='application_upload',
            field=models.FileField(blank=True, upload_to='app_requests/'),
        ),
    ]
