# Generated by Django 3.2.2 on 2021-08-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0005_remove_consultation_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofreading',
            name='research_area',
            field=models.CharField(choices=[('АСТРОНОМИЯ И ПЛАНЕТОЛОГИЯ', 'АСТРОНОМИЯ И ПЛАНЕТОЛОГИЯ'), ('БИОЛОГИЯ', 'БИОЛОГИЯ'), ('БИЗНЕС', 'БИЗНЕС'), ('ХИМИЯ', 'ХИМИЯ'), ('ЭКОЛОГИЯ И НАУКА О ЗЕМЛЕ', 'ЭКОЛОГИЯ И НАУКА О ЗЕМЛЕ'), ('ИНЖЕНЕРИЯ', 'ИНЖЕНЕРИЯ'), ('МЕДИЦИНА', 'МЕДИЦИНА'), ('ФИЗИКА', 'ФИЗИКА'), ('СОЦИАЛЬНЫЕ НАУКИ', 'СОЦИАЛЬНЫЕ НАУКИ'), ('ДРУГОЕ', 'ДРУГОЕ')], max_length=255),
        ),
    ]
