# Generated by Django 3.2.2 on 2021-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0007_language_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPlatformsContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
