# Generated by Django 3.2.2 on 2021-10-11 02:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0008_alter_translation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchplatformscontext',
            name='context_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchplatformscontext',
            name='context_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchplatformscontext',
            name='context_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchplatformscontext',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
