# Generated by Django 3.2.2 on 2021-10-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0009_auto_20211011_0230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchPlatformsContext',
        ),
    ]
