# Generated by Django 3.2.2 on 2021-05-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0009_consultation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizeresearches',
            name='user',
        ),
    ]
