# Generated by Django 3.2.2 on 2021-08-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0007_language_file'),
        ('my_requests', '0010_getgrant'),
    ]

    operations = [
    ]
