# Generated by Django 3.2.2 on 2021-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0010_remove_organizeresearches_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizeresearches',
            options={'verbose_name': 'исследование', 'verbose_name_plural': 'Стратегия исследования'},
        ),
        migrations.AlterField(
            model_name='organizeresearches',
            name='select_topic',
            field=models.CharField(choices=[('стратегия исследования', 'стратегия исследования'), ('Научное сотрудничество', 'Научное сотрудничество'), ('Научное финансирование', 'Научное финансирование'), ('Управление и ведение', 'Управление и ведение')], max_length=100),
        ),
    ]
