# Generated by Django 3.2.2 on 2021-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0012_auto_20210803_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
