# Generated by Django 3.2.2 on 2021-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0013_alter_translation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='char_amount',
            field=models.IntegerField(default=0),
        ),
    ]
