# Generated by Django 3.2.2 on 2021-08-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0014_translation_char_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
