# Generated by Django 3.2.2 on 2021-08-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0009_auto_20210803_2025'),
        ('my_requests', '0015_translationcostmodel'),
    ]

    operations = [
    ]
