# Generated by Django 3.2.2 on 2021-08-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0011_merge_0009_auto_20210803_2025_0010_getgrant'),
        ('my_requests', '0016_merge_20210804_1743'),
    ]

    operations = [
    ]
