# Generated by Django 3.2.2 on 2021-08-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0016_merge_20210804_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='word_amount',
            field=models.IntegerField(default=1),
        ),
    ]
