# Generated by Django 3.2.2 on 2021-08-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0018_remove_translation_word_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizeresearches',
            name='select_topic',
        ),
    ]
