# Generated by Django 3.2.2 on 2021-08-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_requests', '0017_merge_20210805_1430'),
        ('my_requests', '0020_getdesign'),
    ]

    operations = [
    ]
