# Generated by Django 3.2.2 on 2021-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(null=True, verbose_name='amount')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Наличные'), (2, 'Пластиковая карта'), (3, 'Apelsin'), (4, 'Payme')], verbose_name='type')),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(0, 'обрабатывается...'), (1, 'В ожидании'), (2, 'Ошибка'), (3, 'Завершено'), (4, 'Отменен'), (5, 'Истёк'), (6, 'Возвращен')], default=1, verbose_name='status')),
                ('delivery_status', models.PositiveSmallIntegerField(choices=[(1, 'В ожидании'), (2, 'На доставке'), (3, 'Доставлен'), (4, 'Возвращен')], default=1, verbose_name='delivery status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
