# Generated by Django 3.2.2 on 2021-06-02 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True, verbose_name='amount')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Наличные'), (2, 'Пластиковая карта'), (3, 'Click'), (4, 'Payme')], verbose_name='type')),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'В ожидании'), (2, 'Ошибка'), (3, 'Завершено'), (4, 'Отменен'), (5, 'Истёк'), (6, 'Возвращен')], default=1, verbose_name='status')),
                ('delivery_status', models.PositiveSmallIntegerField(choices=[(1, 'В ожидании'), (2, 'На доставке'), (3, 'Доставлен'), (4, 'Возвращен')], default=1, verbose_name='delivery status')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
