# Generated by Django 3.2.2 on 2021-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='source',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
