# Generated by Django 3.2.2 on 2021-06-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210603_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
