# Generated by Django 3.2.2 on 2021-08-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ('-id',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
