# Generated by Django 3.2.2 on 2021-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='madia/files'),
        ),
    ]
