from rest_framework import serializers

from paymeuz.keywords import METHOD_PERFORM_TRANSACTION, METHOD_CREATE_TRANSACTION, METHOD_CHECK_PERFORM_TRANSACTION, \
    METHOD_CHECK_TRANSACTION, METHOD_CANCEL_TRANSACTION

METHOD_CHOICES = (
    (METHOD_CHECK_PERFORM_TRANSACTION, METHOD_CHECK_PERFORM_TRANSACTION),
    (METHOD_CREATE_TRANSACTION, METHOD_CREATE_TRANSACTION),
    (METHOD_CHECK_TRANSACTION, METHOD_CHECK_TRANSACTION),
    (METHOD_PERFORM_TRANSACTION, METHOD_PERFORM_TRANSACTION),
    (METHOD_CANCEL_TRANSACTION, METHOD_CANCEL_TRANSACTION)
)


class PaycomOperationSerialzer(serializers.Serializer):
    id = serializers.IntegerField()
    method = serializers.ChoiceField(choices=METHOD_CHOICES)
    params = serializers.JSONField()
